### ISSUE TITLE
Not provided doctrine types for nullable database type

### ISSUE THREAD

**Issue by demenkov** [FriendsOfDoctrine/dbal-clickhouse#14]
Such as

- Nullable(String)
- Nullable(Float64)
- Nullable(Int32)
- Array(Nullable(String))
- Nullable(UInt8)

etc.

**Comment by demenkov** [comment]
It isn't documented yet, but exists
https://github.com/yandex/ClickHouse/issues/867

**Comment by mochalygin** [comment]
@demenkov How does it work? Where syntax examples can be found?

**Comment by demenkov** [comment]
@mochalygin 
some info can be found here
https://github.com/yandex/ClickHouse/blob/933313aea3d4fa1c217e4191b005055cf6caad0a/doc/example_datasets/nyc_taxi.md

**Comment by argayash** [comment]
@demenkov @mochalygin 
I think it's a good idea to use the `notnull` option in false mode to support `Nullable` ClickHouse types

[added test](https://github.com/FriendsOfDoctrine/dbal-clickhouse/pull/15/files#diff-49667d0651826e105c2d588bcfc62dd6)
