### ISSUE TITLE
Detect PK in MergeTree table fails

### ISSUE THREAD

**Issue by demenkov** [FriendsOfDoctrine/dbal-clickhouse#16]
When I'm trying to create mapping from table in MergeTree by command

`php bin/console doctrine:mapping:import App\\Entity xml --path=config/doctrine --em=clickhouse`

it returns following

```
In DatabaseDriver.php line 288:
                                                                                                 
  Table stat has no primary key. Doctrine does not support reverse engineering from tables that  
   don't have a primary key.                 
```

**Comment by argayash** [comment]
@demenkov 
Can you check with new release v.1.5.1?

**Comment by demenkov** [comment]
@argayash yep, generated normally

**Comment by demenkov** [comment]
I think I found a bug related to https://github.com/FriendsOfDoctrine/dbal-clickhouse/pull/15
When generated annotation for column with nullable type
`utm_source Nullable(String)`
importer creates description of field with nullable=false instead of nullable=true
`<field name="utmSource" type="string" column="utm_source" nullable="false">`

**Comment by argayash** [comment]
@demenkov 
Can you check with new release v.1.5.2?)

**Comment by demenkov** [comment]
@mochalygin yep, works correct)
