### ISSUE TITLE
php8 support?

### ISSUE THREAD

**Issue by 1271** [FriendsOfDoctrine/dbal-clickhouse#43]
Hello. Php8 has been around for half a year, is there any support planned?

Thanks

**Comment by smaknsk** [comment]
```
$ composer require --dev symfony/profiler-pack
Problem 1
    - friendsofdoctrine/dbal-clickhouse is locked to version v1.5.3 and an update of this package was not requested.
    - friendsofdoctrine/dbal-clickhouse v1.5.3 requires php ^7.1 -> your php version (8.0.7) does not satisfy that requirement.
```
trick
`composer require --dev symfony/profiler-pack --ignore-platform-req=php`

**Comment by firestorm23** [comment]
Nice trick if you are working alone on your pet project.

**Comment by texnicii** [comment]
since 1.5.4 version  PHP 8 supported
`composer require friendsofdoctrine/dbal-clickhouse:^1.5.4`

**Comment by asanikovich** [comment]
@1271 @smaknsk @firestorm23 As mentioned above, we have added support PHP 8 in 1.5.4 release.
