### ISSUE TITLE
Deprecated Error with package

### ISSUE THREAD

**Issue by Maxyandr** [FriendsOfDoctrine/dbal-clickhouse#44]
`[
  "exception" => ErrorException {
    #message: "User Deprecated: The "FOD\DBALClickHouse\ClickHouseConnection" class implements "Doctrine\DBAL\Driver\PingableConnection" that is deprecated."
    #code: 0
    #file: "./vendor/symfony/error-handler/DebugClassLoader.php"
    #line: 390
    #severity: E_USER_DEPRECATED
    trace: {
      ./vendor/symfony/error-handler/DebugClassLoader.php:390 { …}
      ./vendor/friendsofdoctrine/dbal-clickhouse/src/Driver.php:57 { …}
      ./vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:398 { …}
      ./vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1938 { …}
      ./vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1276 { …}
      ./vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:212 { …}
      ./src/Command/DistribuneAggregateIncomeCommand.php:65 {
        App\Command\DistribuneAggregateIncomeCommand->getWagesData(): array^
        ›     ->groupBy('v.video, v.publisher');
        › $statisticsData = $qb->execute();
        › 
      }
      ./src/Command/DistribuneAggregateIncomeCommand.php:47 { …}
      ./vendor/symfony/console/Command/Command.php:256 { …}
      ./vendor/symfony/console/Application.php:989 { …}
      ./vendor/symfony/framework-bundle/Console/Application.php:96 { …}
      ./vendor/symfony/console/Application.php:290 { …}
      ./vendor/symfony/framework-bundle/Console/Application.php:82 { …}
      ./vendor/symfony/console/Application.php:166 { …}
      ./bin/console:43 { …}
    }
  }
]
`

**Comment by asanikovich** [comment]
Resolved in the new version https://github.com/FriendsOfDoctrine/dbal-clickhouse/releases/tag/v2.0.0

**Comment by asanikovich** [comment]
@Maxyandr 
Resolved in the new version https://github.com/FriendsOfDoctrine/dbal-clickhouse/releases/tag/v2.0.0
