### ISSUE TITLE
Declaration of Driver::getSchemaManager must be compatible with interface

### ISSUE THREAD

**Issue by SamAntUA** [FriendsOfDoctrine/dbal-clickhouse#45]
https://github.com/FriendsOfDoctrine/dbal-clickhouse/blob/820c38bef41bf508692addfe1e259bb7196d6efe/src/Driver.php#L71

**Fatal error**
Declaration of
FOD\DBALClickHouse\Driver::getSchemaManager(Doctrine\DBAL\Connection $conn)
must be compatible with
Doctrine\DBAL\Driver::getSchemaManager(
    Doctrine\DBAL\Connection $conn,
    Doctrine\DBAL\Platforms\AbstractPlatform $platform
)

[Since v3.0.0 of Doctrine/DBAL (JUL, 2020) AbstractPlatform became a required arg](https://github.com/doctrine/dbal/commit/c1ed9fe550e159d28e84bee471662262c2a0447a)

**Comment by asanikovich** [comment]
Version https://github.com/FriendsOfDoctrine/dbal-clickhouse/releases/tag/v2.0.0 ready for you.
