### ISSUE TITLE
DBAL 2.7 is no longer maintained

### ISSUE THREAD

**Issue by powernic** [FriendsOfDoctrine/dbal-clickhouse#55]
When do you plan to add support for DBAL 3.5 and above?

**Comment by sarbazx** [comment]
<img width="1578" alt="CleanShot 2023-02-19 at 00 53 22@2x" src="https://user-images.githubusercontent.com/5629946/219901101-5769a25b-5e17-4c80-8c9c-08b55b536caa.png">

can't install latest version

**Comment by alexinteam** [comment]
Hello any update for DBAL 3.5 and above?

**Comment by kliker02** [comment]
+

**Comment by asanikovich** [comment]
@powernic @sarbazx @alexinteam @kliker02 
Version https://github.com/FriendsOfDoctrine/dbal-clickhouse/releases/tag/v2.0.0 ready for you.
