### ISSUE TITLE
Does not support config readonly https sslCA 

### ISSUE THREAD

**Issue by raymond-tnc** [FriendsOfDoctrine/dbal-clickhouse#65]
src/ClickHouseConnection.php:42 
first params  only have  "host port username password"
but actually it also support other params "config readonly https sslCA"

**Comment by asanikovich** [comment]
Fixed in https://github.com/FriendsOfDoctrine/dbal-clickhouse/pull/71

**Comment by asanikovich** [comment]
@raymond-tnc Fixed in https://github.com/FriendsOfDoctrine/dbal-clickhouse/pull/71
